name: material_pickers
description: Material pickers for Flutter.
version: 0.0.2
author: "Lung Razvan (long1eu)<lung.razvan@gmail.com>"
homepage: http://www.long1.eu

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^0.12.0

flutter:

  assets:
    - res/images/placer.png